sudo: required
dist: bionic
services:
  - xvfb
addons:
  chrome: stable
language: node_js
node_js:
  - "12.14.0"

before_install:
    # setting the path for phantom.js 2.0.0
    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
    - "npm config set spin false"
    - "npm install -g npm@^3"
install:
    - mkdir travis-phantomjs
    - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
    - export PATH=$PWD/travis-phantomjs:$PATH
    - npm install
    - npm install -g grunt
    - grunt build
    - mkdir $TRAVIS_BRANCH && tar -cvzf $TRAVIS_BRANCH/banana-$TRAVIS_BRANCH.tar.gz dist
script:
    - npm run test-single-run

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: ca-central-1
    bucket: "io.aadel.banana"
    skip_cleanup: true
    local_dir: $TRAVIS_BRANCH
    on:
      branch: $TRAVIS_BRANCH
  - provider: script
    script: "curl -H 'Content-Type: application/json' -X POST -d '{\"docker_tag\": \"$TRAVIS_BRANCH\"}' 'https://hub.docker.com/api/build/v1/source/f3ae180f-58a9-4799-80ba-b5dd128ac905/trigger/8cb4e293-28bb-4646-8fe6-30232f31d05a/call/'"
    on:
      branch: $TRAVIS_BRANCH
