sudo: required
dist: bionic
services:
  - xvfb
addons:
  chrome: stable
language: node_js
node_js:
  - "12.14.0"

before_install:
    # setting the path for phantom.js 2.0.0
    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
    - "npm config set spin false"
    - "npm install -g npm@^3"
install:
    - mkdir travis-phantomjs
    - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
    - export PATH=$PWD/travis-phantomjs:$PATH
    - npm install
    - npm install -g grunt
    - grunt build
    - cd dist && tar -cvzf banana-dist.tar.gz *
script:
    - npm run test-single-run

deploy:
  provider: s3
  bucket: "io.aadel.banana"
  skip_cleanup: true
  upload-dir: $TRAVIS_BRANCH
  acl: public_read
  file_glob: true
  glob: banana-dist.tar.gz
  on:
    branch: $TRAVIS_BRANCH
